Lesson04-VAD/Lesson04-VAD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson04_VAD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lesson04-VAD/Lesson04-VAD/Controllers/VadStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson04_VAD.Controllers
{
    public class VadStudentController : Controller
    {
        /// <summary>
        /// Author: Vũ Anh Dương
        /// </summary>
        /// <returns></returns>
        // GET: VadStudent
        public ActionResult Index()
        {
            ViewBag.fullName = "Vũ Anh Dương";
            ViewData["Birthday"] = "25/10/2004";
            TempData["Phone"] = "0972471680";
            return View();
        }
        
        public ActionResult Details()
        {
            string vadStr = "";
            vadStr += "<h3>Họ và tên: Vũ Anh Dương </h3>";
            vadStr += "<p> Mã sv: 2210900017 </p>";
            vadStr += "<p> Địa chỉ mail: vuanhduong251020042@gmail.com </p>";

            ViewBag.Details = vadStr ;

            return View("chiTiet");
        }

        public ActionResult NgonNguRazor()
        {
            return View();
        }

        // HTMLHelper
        // GET: VadStudent/AddNewStudent
        public ActionResult AddNewStudent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewStudent(FormCollection form)
        {
            //lấy dữ liệu trên form
            string fullname = form["fullName"];
            string masv = form["maSV"];
            string taikhoan = form["Taikhoan"];
            string matkhau = form["Matkhau"];

            string vadStr = "<h3>" + fullname + "</3>";
            vadStr += "<p>" + masv;
            vadStr += "<p>" + taikhoan;
            vadStr += "<p>" + matkhau;

            ViewBag.info = vadStr;
            return View("Ketqua");
        }
    }
}

Lesson04-VAD/Lesson04-VAD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Vũ Anh Dương", "Index", "VadStudent", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "VadStudent", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("VadStudent", "Index", "VadStudent", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Chi tiết", "Details", "VadStudent", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Razor", "NgonNguRazor", "VadStudent", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add new Student", "AddNewStudent", "VadStudent", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lesson04-VAD/Lesson04-VAD/Views/VadStudent/AddNewStudent.cshtml
@{
    ViewBag.Title = "Thêm mới sinh viên";
}

<h2>Thêm mới sinh viên</h2>
<hr />
@using (Html.BeginForm())
{
    <div>
        @Html.Label("Họ tên")
        @Html.TextBox("fullName")
    </div>
    <div>
        @Html.Label("Mã số")
        @Html.TextBox("maSV")
    </div>
    <div>
        @Html.Label("Tài khoản")
        @Html.TextBox("Taikhoan", "", new {@class = "form-control"})
    </div>
    <div>
        @Html.Label("Mật khẩu")
        @Html.Password("Matkhau")
    </div>
    <button>Submit</button>
}

Lesson04-VAD/Lesson04-VAD/Views/VadStudent/Index.cshtml
@{
    ViewBag.Title = "Vũ Anh Dương - Index";
}

<h2>Vũ Anh Dương - Index</h2>
<hr/>
<h3>Hiển thị dữ liệu lấy từ Action trong Controller</h3>
<h4>FullName: @ViewBag.fullName</h4>
<h4>Ngày sinh: @ViewData["Birthday"]</h4>
<h4>Di động: @TempData["Phone"]</h4>

Lesson04-VAD/Lesson04-VAD/Views/VadStudent/Ketqua.cshtml
@{
    ViewBag.Title = "Ketqua";
}

<h2>Kết quả</h2>
@Html.Raw(ViewBag.info)

Lesson04-VAD/Lesson04-VAD/Views/VadStudent/NgonNguRazor.cshtml
@{
    ViewBag.Title = "Ngôn ngữ Razor";
}

<h2>Ngôn ngữ Razor</h2>
<h3>Biến</h3>
@{
    var name = "Vũ Anh Dương";
    int age = 20;
    DateTime dt = DateTime.Now;
}
<p>Họ tên: @name</p>
<p>Tuổi: @age</p>
<p>Time: @dt</p>
<hr />
<h3>Câu lệnh if</h3>
@{
    if (age > 40)
            {
                <p>Già rồi</p>
            }
    else
            {
                <p>Còn trẻ</p>
            }
}
<hr />
<h3>Loop: for, while, do....while, foreach....</h3>
@{ 
    int num = 10;
}
    @for (int i = 0; i<num; i++)
            {
                <li>@i = > @i*@i</li>
            }
<hr />
<h3>Mảng</h3>
@{ 
    string[] names = { "Trần Văn A", "Nguyễn Thị B", "Lê Đại C", "Trần Thị D" };
}
@foreach (var item in names)
            {
                <p>@item</p>
            }

Lesson04-VAD/Lesson04-VAD/Views/VadStudent/chiTiet.cshtml
@{
    ViewBag.Title = "Thông tin chi tiết sinh viên";
}

<h2>Thông tin chi tiết sinh viên</h2>
<hr />
@Html.Raw(ViewBag.Details)